### ISSUE TITLE
Running a development build of the Wallet against Ropsten fails

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#66]
It seems to fail in truffle with the following error: 
```ERROR:

ERROR: /Users/alexgap/code/apps/packages/wallet/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/src/index.js:50
      throw new Error("Mnemonic invalid or undefined");
^
Error: Mnemonic invalid or undefined
    at new v (/Users/alexgap/code/apps/packages/wallet/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/src/index.js:50:1)
    at Object.provider (/Users/alexgap/code/apps/packages/wallet/truffle.js:28:23)
    at Object.create (/Users/alexgap/code/apps/packages/wallet/node_modules/truffle/build/webpack:/packages/truffle-provider/index.js:15:1)
    at Config.get [as provider] (/Users/alexgap/code/apps/packages/wallet/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:202:1)
    at Object.detect (/Users/alexgap/code/apps/packages/wallet/node_modules/truffle/build/webpack:/packages/truffle-core/lib/environment.js:59:1)
    at Object.<anonymous> (/Users/alexgap/code/apps/packages/wallet/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:170:1)
    at cb (util.js:1420:39)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by lalexgap** [comment]
This was due to the fact that I didn't have a proper `mnemonic` defined. Once I used one from `https://iancoleman.io/bip39/` it worked. I'm not sure why this isn't the case in `rps` as that seems fine without the `mnemonic`

Maybe we want to define a default mnemonic for the test nets?
